export const RUN_SEQUENCE = '@@RUN_SEQUENCE';

export const CATEGORY_SELECT = 'CATEGORY_SELECT';
export const LOAD_CATEGORIES_REQUEST = 'LOAD_CATEGORIES_REQUEST';
export const LOAD_CATEGORIES_RESOLVE = 'LOAD_CATEGORIES_RESOLVE';
export const LOAD_CATEGORIES_REJECT = 'LOAD_CATEGORIES_REJECT';

export const TODO_DONE_TOGGLE = 'TODO_DONE_TOGGLE';
export const TODO_SAVE = 'TODO_SAVE';
export const TODO_DELETE = 'TODO_DELETE';
export const TASK_DELETE_CONFIRM = 'TASK_DELETE_CONFIRM';

export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_ADD_CHANGE = 'CATEGORY_ADD_CHANGE';
export const FAILURE = 'FAILURE';